### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by vladosam** [slurdge/docker-keewebdav#2]
Hi, i'm trying to test your docker image with `docker run -p 8080:8080 slurdge/keewebdav` but once i open http://IP:8080 all don't get anything on screen. Just white screen and nothing on it. Only favicon in visible on tab. Also is there some instructions how to use my wildcard certificate with caddy not the one from letsencrypt? Thanks.

**Comment by slurdge** [comment]
Hello, I just tried the exact command you pasted and it works on two different computers. Can you try with other docker images ? The only thing I can think of is that you have a firewall preventing access to the page.

If you want to use your own wildcard, then you would need to mount the `Caddyfile`  (which is at `/etc/Caddyfile`) and put a section with your certificate. Also don't forget to mount your certificates inside the docker.

**Comment by vladosam** [comment]
I tried other some other keeweb images and they work fine. So i don't think it's firewall problem. But I get this error in developer tools `Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").`

**Comment by slurdge** [comment]
Ah, can you try to access http://localhost:8080/ and tell me if it works ?

**Comment by slurdge** [comment]
The script-src hash should be patched automatically but maybe there's a bug.

See here: https://github.com/slurdge/docker-keewebdav/blob/master/Dockerfile#L28

**Comment by vladosam** [comment]
I can't. It's on headless server. I can curl http://localhost:8080 and I get whole index file.

**Comment by slurdge** [comment]
You could try to port forward your 8080 through SSH if you want to confirm, but I'm pretty sure that newer browsers block what they believe less secure from more secure web.
I have the same issue as you if I access through IP and not through localhost.

For now I don't have a solution, as I don't see what I should change to the Security Policy without making it less secure, this is definitely not what you want.

If you manage to have a https in front of it, I'm quite sure it would work.

**Comment by slurdge** [comment]
I just tested vanilla keeweb with a simple python webserver and the bug is the same, you could try to ask the question at keeweb/keeweb and see if they have a suggestion

**Comment by vladosam** [comment]
I'll try it tomorrow with traefik or npm in front of it. I'll report back to you.

**Comment by vladosam** [comment]
I tested with npm and everything works wooohooo. Thanks. Closing this.
